#!/usr/bin/env bun
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const SKILL_DIR = join(REPO_ROOT, "skill");
const EMBEDDED_PATH = join(REPO_ROOT, "src", "embedded.ts");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fp = join(dir, entry);
    const st = statSync(fp);
    if (st.isDirectory()) out.push(...walk(fp));
    else out.push(fp);
  }
  return out;
}

function generateEmbedded(): number {
  const files = walk(SKILL_DIR);
  const entries = files.map((fp) => {
    const rel = relative(SKILL_DIR, fp).split("\\").join("/");
    const content = readFileSync(fp, "utf8");
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(content)}`;
  });
  const code = `// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
export const EMBEDDED_SKILL_FILES: Record<string, string> = {
${entries.join(",\n")}
};
`;
  writeFileSync(EMBEDDED_PATH, code, "utf8");
  return files.length;
}

async function compile(): Promise<void> {
  const proc = Bun.spawn(
    ["bun", "build", "--compile", "./src/index.ts", "--outfile", "retro"],
    { cwd: REPO_ROOT, stdout: "inherit", stderr: "inherit" },
  );
  const code = await proc.exited;
  if (code !== 0) process.exit(code);
}

const mode = process.argv[2] ?? "all";
if (mode === "generate") {
  const n = generateEmbedded();
  console.log(`✓ generated ${EMBEDDED_PATH} with ${n} files`);
} else if (mode === "compile") {
  await compile();
  console.log(`✓ compiled ./retro`);
} else {
  const n = generateEmbedded();
  console.log(`✓ generated ${EMBEDDED_PATH} with ${n} files`);
  await compile();
  console.log(`✓ compiled ./retro`);
}
